
-- Remove existing PWI universities
DELETE FROM universities;

-- Insert HBCUs
INSERT INTO universities (name) VALUES
  ('Alabama A&M University'),
  ('Alabama State University'),
  ('Albany State University'),
  ('Alcorn State University'),
  ('Benedict College'),
  ('Bennett College'),
  ('Bethune-Cookman University'),
  ('Bowie State University'),
  ('Central State University'),
  ('Cheyney University of Pennsylvania'),
  ('Claflin University'),
  ('Clark Atlanta University'),
  ('Coppin State University'),
  ('Delaware State University'),
  ('Dillard University'),
  ('Edward Waters University'),
  ('Elizabeth City State University'),
  ('Fayetteville State University'),
  ('Fisk University'),
  ('Florida A&M University'),
  ('Florida Memorial University'),
  ('Fort Valley State University'),
  ('Grambling State University'),
  ('Hampton University'),
  ('Harris-Stowe State University'),
  ('Howard University'),
  ('Huston-Tillotson University'),
  ('Jackson State University'),
  ('Johnson C. Smith University'),
  ('Kentucky State University'),
  ('Lane College'),
  ('Langston University'),
  ('Le Moyne-Owen College'),
  ('Lincoln University (MO)'),
  ('Lincoln University (PA)'),
  ('Livingstone College'),
  ('Meharry Medical College'),
  ('Miles College'),
  ('Morgan State University'),
  ('Morehouse College'),
  ('Morris Brown College'),
  ('Morris College'),
  ('Norfolk State University'),
  ('North Carolina A&T State University'),
  ('North Carolina Central University'),
  ('Oakwood University'),
  ('Paine College'),
  ('Paul Quinn College'),
  ('Philander Smith University'),
  ('Prairie View A&M University'),
  ('Rust College'),
  ('Savannah State University'),
  ('Shaw University'),
  ('South Carolina State University'),
  ('Southern University and A&M College'),
  ('Spelman College'),
  ('St. Augustine''s University'),
  ('Stillman College'),
  ('Talladega College'),
  ('Tennessee State University'),
  ('Texas Southern University'),
  ('Tougaloo College'),
  ('Tuskegee University'),
  ('University of Arkansas at Pine Bluff'),
  ('University of Maryland Eastern Shore'),
  ('University of the District of Columbia'),
  ('University of the Virgin Islands'),
  ('Virginia State University'),
  ('Virginia Union University'),
  ('Voorhees University'),
  ('West Virginia State University'),
  ('Wilberforce University'),
  ('Wiley College'),
  ('Winston-Salem State University'),
  ('Xavier University of Louisiana');
