// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgqnjhnukbuaboabhbtf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncW5qaG51a2J1YWJvYWJoYnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NDkxOTAsImV4cCI6MjA5MTMyNTE5MH0.x8g-pd3DWfNB2-l2r4bSlgV9ddmYQ58p-JC1l-i9gVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using 'any' temporarily until database migrations are applied and types are regenerated
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});